### ISSUE TITLE
アイマスハッカソン2018 in 大阪

### ISSUE THREAD

**Issue by kaibasira** [imas/hackathon#82]
## テーマ
- アイマスハッカソン2018 in 大阪

## これは何
- アイマスハッカソンを大阪でやってみちゃったりして

## Connpass
<https://imas.connpass.com/event/80082/>

### 日時
- 2018年3月10日(土)

### 場所
- さくらインターネット様

### 以下、今後TTなどを書く……

**Comment by kaibasira** [comment]
## 顔合わせキックオフ@2018/1/15 21:00〜
### Agenda
### 参加者
- ぼでー
- もめん
- うろう
- はむ
- cromisa
- ごっち

### 目的
- メンバーの顔わせ、コンセプトのシェア、役割配分、ざっとやること

### コンセプト
- テーマをなんか設けてみたい
  - ex.) 担当アイドルの○○を○○　みたいな
- 景品的な何かを出してみるかな？

### スタッフの役割(勝手に決めた)
- BGM,配信
  - cromisa
- 食事、懇親会
  - もめん、はむ、ごっち
- 受付
  - うろう
- 司会的な
  - ぼでー

**Comment by crssnky** [comment]
#### アイマス食の前回の復習
> ドーナツ,うろうP自作レモンタルト,メローイエロー、もやし、カリカリ梅、カロリーメイト、フライドポテト、サクマ式ドロップス、わたあめ、焼きマシュマロ、アップルパイ、きのこ山、…たけのこの里、プチシュー、ミックスナッツ。

**Comment by adachi-tsukasa** [comment]
#### 先日会場を提供してくださる妖介さんと、会場で提供する飲食に関する会話の要約
- グランフロント（会場のビル）内で食事を提供できる場所がある

  - 入居企業向けだがイベントであれば対応してくれる。予算、規模も柔軟に対応可能とのこと。

  - meetup京都のようなカジュアルな飲食であれば、前回同様ケータリングの方が良いかも。と助言いただきました。

→食事提供の場所は借りず、今まで同様にハッカソン会場内での飲食を行う方向とします。
ハッカソン会場内には冷蔵庫（社員の方のみ使用可）があり、使用について別途相談します。

**Comment by crssnky** [comment]
アイマス食募集結果(+思いついたの)
- もやし
- 中華料理
- ハンバーガー
- ハンバーグ
- おにぎり
- カレー
- プチシュー
- マシュマロ
- おはぎ
- 紅茶
- たこ焼き
- たい焼き
- スシ
- カレイの煮付け
- アメ
- あんきも

**Comment by adachi-tsukasa** [comment]
## スタッフ's TODO
### もめん's Task
- [ ] 妖介さんと会場に関する質問
  - [x] 出入り時間の確認
  - [ ] ビル入りから会場までのアテンド方法
  - [ ] 会場注意事項の確認
- [x] connpassでの告知案の作成
- [ ] スポンサー様との連絡

### cromisa's Task (司会、音楽操作担当)
- [ ] 開始・終了時の司会スライド作成
- [ ] 使用音楽選定（LT発表者との連絡）

### うろうP's Task (受付、財務担当)
- [ ] 受付に必要なモノを揃える（ぼでーさん持ちのモノどうしましょうか…25日までに相談）
- [ ] お釣りを用意する
- [ ] 二次会会場選定（妖介さんに相談しても良さそう
。そう言えばhamacoさんが飲めるところがあるって言ってたな…）
- [ ] 高垣家を感じる

### はむ's Task (飲食手配担当)
- [ ] 食べ物決め（3月初週にでも決めておきたいですね…！）
- [ ] （ピザ？）注文する
- [ ] 飲み物決める、注文する
- [ ] 宮本家を感じる２

### ごっち's Task (雑貨担当、各種補佐担当)
- 人手不足になったところでお手伝いお願いします！
- [ ] 必要雑貨準備（各所より依頼が来た場合に）
- [ ] 当日の会場アテンド

### 大体のスタッフの動きと人が要るタイミング
- 準備中

**Comment by crssnky** [comment]
2018/02/26 connpass送信メッセージ
```
こんばんは!

この度は「アイマスハッカソン2018 in 大阪」にご参加登録して頂きありがとうございます!
冬季オリンピックも終え、3月が近づいて、ハッカソンまで残り2週間を切りました。
今回は、当日のプロダクトのヒントとなるようなものをご案内させていただきます!

1. IM@Study Repositories(https://github.com/imas)
こちらでは、IM@Studyへ登録されたプロダクトがあります。
当日作るもののアイデアの参考であったり、cloneすることで使えるものであったりと、お力添えできると思います。
また、hackthonリポジトリのarchivesディレクトリに過去の成果物が少し入っています。合わせてご参照ください。

2. デレマス呼称表(https://calltable.imascg.moe/)
(バックエンド:https://github.com/ktnyt/imascg)
(フロントエンド:https://github.com/ktnyt/cg-call-table)
ktnytさんの管理する呼称表APIです。
https://calltable.imascg.moe/
見える形はこちら↑
https://api.imascg.moe/
こちらへリクエストすることで、使うこともできます。
ktnytさんより
「バックエンドの拡張を今度予定していますが、データの流し込みで色々ゴニョっているので、見識がある方からの助言があると嬉しいです。」

3. im@sparql(https://sparql.crssnky.xyz/imas/)
私、croMisaの管理するアイマスのオープンデータです。
SPARQLというSQLに似た言語を使うことで、アイマス世界を検索できるように目指しています。
ちょっとだけ詳しい説明はこちら
http://crssnky.hatenablog.jp/entry/2017/12/06/000000

以上の3点です。
私の知ってる範囲での紹介ですので、他にも使えそうなものがあればドンドン使ってください。当日は、様々なものが生まれてくると期待しています!

LTの参加ですが、絶賛募集中です!
参加の際はIM@Studyの#hackathon2018osakaチャンネル、
もしくはtwitterよりスタッフのmomen(@momen_666)かcromisa(@croMisa)に一声頂ければと思います。

最後になりますが、参加登録数が満員20名になり、大変嬉しく思います。
大阪でも、前回のアイマスハッカソン2017in東京に負けないくらい楽しんでいただけるイベントにしたいと思っています!
スタッフも精一杯サポートいたしますので、何卒よろしくお願いします!
ご不明な点などございましたら、お気軽にご相談ください!
当日、皆様とお会い出来ることを楽しみにしております!

追記:
自己紹介のページを集約する試みもやっておりますので、githubアカウントをお持ちの方は以下を参考に是非ご登録ください。
https://github.com/imas/hackathon/wiki/%E3%83%97%E3%83%AD%E3%83%87%E3%83%A5%E3%83%BC%E3%82%B5%E3%83%BC%E8%87%AA%E5%B7%B1%E7%B4%B9%E4%BB%8B%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
```

**Comment by hamup8** [comment]
食事関連についてまとめました！

- 購入場所
  - ピザ：ドミノ・ピザ
  - お酒：カクヤス


**ピザ (Lサイズ9枚)**
3456円/1枚
3456 * 9枚 * 0.59(41%OFFクーポン適用) = 18,351円

**ビール (340ml缶24本)**
2,862円/24缶ケース
2,862 * 1 = 2,862円

**チューハイ(350ml缶10本)**
117円/1本
117 * 10 = 1,170円

**ハイボール(350ml缶5本)**
192円/1本
192 * 10 = 960円

**ソフドリ(1Lペットボトル3本)**
210円/3本
210 * 3 = 620円

ハッカソン中のお菓子
1000円ぐらい

計 24,963円

ピザと飲み物の受け取り時間は1700-1730を予定してます。

**Comment by adachi-tsukasa** [comment]
以下スポンサー様確定しました。
- 株式会社grooves様
- Crono,Inc

**Comment by YutaGoto** [comment]
## スタッフスケジュール

| 時刻    | 内容                           | スタッフ                                                     |
| ------- | ------------------------------ | ------------------------------------------------------------ |
| 9:30    | スタッフ+ 妖介P 集合、会場準備  | 会場準備をする[イス机、プロジェクター、マイク、受付、音楽など] |
| 10:00   | 開場 受付開始                  | 受付担当、席誘導、開始前の諸注意アナウンス                   |
| 10:30   | オープニング                   | 司会とスタッフ紹介                                           |
| 11:00   | 開発開始、アイディアソン       | 音楽、アイディアソンの進行係、                               |
| 12:00   | 昼食のアナウンス               | 司会、昼食誘導                                               |
|         | 引き続き開発をする             |                                                              |
|         | LTの登壇者を募る               | 司会                                                         |
| 17:30頃 |                                | 食事、飲み物の準備、机の移動                                 |
| 18:00   | 乾杯の音頭                     | 司会、飲み物を配る                                           |
| 18:30   | 成果発表LT                     | 司会、動画配信                                               |
|         | 途中休憩                       |                                                              |
| 20:00   | まとめ、中締め、この後の諸注意 | 司会                                                         |
|         |                                | 机イスの復帰、ゴミの片付け、忘れ物確認、打ち上げ会場への誘導 |
| 20:30   | 打ち上げ開始                   |                                                              |

**Comment by hamup8** [comment]
### 懇親会の候補
- 鹿児島県霧島市　塚田農場　梅田ギャザ阪急店
https://www.hotpepper.jp/strJ001145312/

- 新世界じゃんじゃん 梅田店
https://r.gnavi.co.jp/c043902/

**Comment by crssnky** [comment]
### セットリスト
1. チェリー
2. Welcome!!(全員)
3. ススメ☆オトメ～jewel parade～(Cinderella Project)
4. DRIVE A LIVE(Jupiter)
5. Light Year Song
6. ココロ☆エクササイズ
7. お散歩カメラ
8. サ・ヨ・ナ・ラ Summer Holiday
9. ザ・ライブ革命でSHOW!
10. 夜に輝く星座のように
11. Memories
12. String of Fate
13. 待ち受けプリンス
14. 星屑のシンフォニア
15. Orange Sapphire
16. Piece Montee
17. 神さまのBirthday
18. NO CURRY NO LIFE
19. 恋のHamburg♪
20. À La Carte FREEDOM♪
21. 愛 LIKE ハンバーガー
22. 満腹至極フルコォス
23. 共鳴世界の存在論
24. GOLD ～No.79～
25. Funny Logic
26. Eternal Spiral
27. メルヘンデビュー!
28. Because
29. キミ＊チャンネル
30. Princess Be Ambitious!!
31. Radio Happy
32. 強く尊き獣たち
33. トリプルAngel
34. To...
35. 明日また会えるよね
36. MOON NIGHTのせいにして
37. Little Match Girl
38. Sweet Sweet Soul
39. アタシポンコツアンドロイド
40. Flowing Freedom
41. G♡F
42. Raise the FLAG
43. ラヴィアンローズ
44. カレイドTOURHYTHM
45. SMOKY FRUITS
46. Super Lover
46. 絶対特権主張しますっ!
47. RULE ～牙ヲ穿テヨ～
48. 放課後ジャンプ
49. 昏き星、遠い月
50. とんでいっちゃいたいの
51. Study Equal Magic!
52. Good-Byes
53. CAT CROSSING
54. Love∞Destiny
55. 夢色VOYAGER
56. FAKE SELF×TRUE SELF
57. 恋の音色ライン
58. 咲いてJewel
59. SSweep Your Gloom
60. relations
61. 瑠璃色金魚と花菖蒲
62. Nation Blue
63. JOKER↗オールマイティ
64. Kosmos, Cosmos
65. piece of cake
66. Hotel Moonside(Extended Version)
67. フェイバリットに踊らせて
68. アマテラス
69. ハミングバード
70. STORY
71. オレたちの最強伝説〜一世一代、破羅駄威棲!〜
72. 99 Nights
73. Marionetteは眠らない
74. あんずのうた
75. "HELLO!!"
76. WORLD WIDE DANCE!!!
77. Understand? Understand!
78. One Life
79. Legacy of Sprit
80. キラメキラリ
81. Happy Darling
82. Romantic Now
83. ∞ Possibilities
84. 乙女よ大志を抱け!!
85. fruity love
86. 秘密のトワレ
87. The 1st Movement ～未来のための二重奏～
88. 静かな夜に願いを...
89. 秘密のメモリーズ
90. スローライフ・ファンタジー
91. Echoes My Note
92. 10thAnniversaryMix
